# Generated by Django 4.1.7 on 2023-04-06 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_group_remove_profile_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
