# Generated by Django 4.1.7 on 2023-04-06 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id_user',
            new_name='user',
        ),
    ]
