# Generated by Django 4.1.7 on 2023-04-06 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
    ]
