# Generated by Django 4.1.6 on 2023-05-07 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_post_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
