# Generated by Django 4.1.6 on 2023-05-07 18:28

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_comment_author_comment_comment_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment_content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='comment_created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='post_content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='post_image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='likes_count',
            new_name='post_likes_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.AddField(
            model_name='post',
            name='post_created_at',
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, related_name='profiles_liking_posts', to='core.post'),
        ),
    ]
