# Generated by Django 4.1.6 on 2023-05-08 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_content_comment_comment_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
