# Generated by Django 4.1.6 on 2023-04-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_profile_gender_profile_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='default_profile_picture.png', upload_to='profile_images/'),
        ),
    ]
