# Generated by Django 4.1.6 on 2023-04-12 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='grouppost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='grouppost',
            name='group',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='privacy_settings',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='privacy_settings',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupMember',
        ),
        migrations.DeleteModel(
            name='GroupPost',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
