# Generated by Django 4.1.6 on 2023-04-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_groupmember_group_remove_groupmember_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(upload_to='profile_images/'),
        ),
    ]
