# Generated by Django 4.1.7 on 2023-05-11 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_comment_comment_author_alter_post_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='comment_for_post',
        ),
    ]
