# Generated by Django 4.1.6 on 2023-04-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'He/Him'), ('F', 'She/Her'), ('T', 'They/Them'), ('O', 'Other'), ('N', 'Prefer not to say'), ('-', 'Not Declared')], default='-', max_length=1),
        ),
    ]
