# Generated by Django 4.1.7 on 2023-05-11 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_comment_comment_for_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_for_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_on_post', to='core.post'),
        ),
    ]
