# Generated by Django 4.1.6 on 2023-04-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('O', 'Other'), ('M', 'He/Him'), ('F', 'She/Her'), ('H', '(hidden)'), ('T', 'They/Them'), ('N', 'Prefer not to say')], default='N', max_length=1),
        ),
    ]
