# Generated by Django 4.1.6 on 2023-05-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_comment_comment_for_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
