# Generated by Django 4.1.6 on 2023-04-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('O', 'Other'), ('M', 'He/Him'), ('F', 'She/Her'), ('T', 'They/Them'), ('N', 'None selected')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, choices=[('O', 'Student'), ('M', 'Working'), ('F', 'Not Working'), ('T', 'Other'), ('N', 'None selected')], default='N', max_length=50, null=True),
        ),
    ]
