# Generated by Django 4.1.6 on 2023-04-18 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_profile_gender_alter_profile_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='modified_date',
        ),
    ]
