# Generated by Django 4.1.6 on 2023-05-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_post_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_author_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_api_view_images/'),
        ),
    ]
