# Generated by Django 4.1.6 on 2023-05-15 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_post_post_author_image_remove_post_post_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='liked_posts',
        ),
    ]
