# Generated by Django 4.1.6 on 2023-04-18 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_created_date_comment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
