# Generated by Django 4.1.6 on 2023-04-21 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
