# Generated by Django 4.1.6 on 2023-05-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_post_post_title_alter_post_post_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlist',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='friendlist',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='sender',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, choices=[('O', 'Student'), ('M', 'Working'), ('F', 'Not Working'), ('T', 'Other'), ('N', 'None selected')], default='N', max_length=50),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='FriendList',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
