# Generated by Django 4.1.6 on 2023-05-17 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_post_post_likes_alter_post_post_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
