# Generated by Django 4.1.6 on 2023-05-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_post_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
