# Generated by Django 4.1.6 on 2023-05-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_comment_post_post_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=models.TextField(max_length=100),
        ),
    ]
