# Generated by Django 4.1.6 on 2023-05-18 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_comment_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_on_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_for_post', to='core.post'),
        ),
    ]
