# Generated by Django 4.1.6 on 2023-05-18 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_comment_comment_on_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_comments',
        ),
    ]
