# Generated by Django 4.1.6 on 2023-05-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_post_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_comments',
            field=models.ManyToManyField(related_name='commented_posts', to='core.comment'),
        ),
    ]
