# Generated by Django 4.1.7 on 2023-05-29 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0034_alter_friendship_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='status',
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('friendship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_request', to='core.friendship')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sender', 'friendship')},
            },
        ),
    ]
