# Generated by Django 4.1.6 on 2023-06-06 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0040_alter_friendship_friendship_receiver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='friendship_receiver',
            new_name='receiver',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='friendship_sender',
        ),
        migrations.AddField(
            model_name='friendship',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiated_friendships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('sender', 'receiver')},
        ),
    ]
