# Generated by Django 4.1.6 on 2023-06-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_rename_friendship_receiver_friendship_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='status',
        ),
    ]
