# Generated by Django 4.1.6 on 2023-06-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_friendship_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(choices=[('O', 'Student'), ('M', 'Working'), ('F', 'Not Working'), ('T', 'Other'), ('N', 'None selected')], default='N', max_length=50),
        ),
    ]
